version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  spark:
    build: .
    container_name: spark_app
    depends_on:
      - postgres
    environment:
      - SPARK_MASTER_HOST=local[*]
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
      - POSTGRES_HOST=postgres_db
    networks:
      - my_network
    volumes:
      - .:/src
    ports:
      - "4040:4040"

  adminer:
    image: adminer
    container_name: adminer_db
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - my_network

networks:
  my_network:

volumes:
  postgres_data: